title: The Fastest Mouse Clicker for Windows
logo: /favicon_large.png
description: Official Download for free and fast, open source, full-featured, statically-linked mouse auto clicker for Windows written in vanilla C++. Uses hardware-limited arrayed Win32 <code><a href="https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput" target="_blank">SendInput()</a></code> calls to reach up to 100000 clicks/s. Supports command line, random clicks and record-play the sequences of clicks.
show_downloads: true
theme: jekyll-theme-minimal
author: Open Source Developer Masha Novedad
tagline: The Fastest Mouse Clicker for Windows
